### ISSUE TITLE
SAM3X8E shield pin map errors

### ISSUE THREAD

**Issue by ozzyman** [grblHAL/SAM3X8E#12]
The shield pin maps for SAM3X8E have pins A.00 and A.01 swapped. PA0 (A.00) is CANTX, and PA1 (A.01) is CANRX.
The correct pin sequence on Due connector P10 is:

Pin    Port   Fn
1       B.17   A8
2       B.18   A9
3       B.19   A10
4       B.20   A11
5       B.15   DAC0
6       B.16   DAC1
7       A.01   CANRX
8       A.00   CANTX

**Comment by terjeio** [comment]
Fixed now.
