### ISSUE TITLE
BESC Spindles

### ISSUE THREAD

**Issue by irshadmgs011** [grblHAL/SAM3X8E#14]
i want to make a pcb engraving machine with arduino due, please add BESC Spindles, and tmc driver 
support

**Comment by terjeio** [comment]
[ESC spindle](https://github.com/grblHAL/drivers) is already supported.

I do not have the hardware for testing the TMC low-level interfaces, there are at least four variants. You can try to add the one you need yourself by copying/modifying code from another driver?

**Comment by irshadmgs011** [comment]
ok , thanks for quick reply
