### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by Ramr93** [grblHAL/SAM3X8E#16]
hi I'm trying to compile using Arduino IDE  for sam3X8E.  I add all the libraries . but it gives tons of error . please help me to compile with steps

**Comment by terjeio** [comment]
See the [Wiki](https://github.com/grblHAL/core/wiki/Compiling-grblHAL).

**Comment by Ramr93** [comment]
i tried BOSSA 1.9.1 also but i didn't work. the port is connected but it shows following error 
![Untitled](https://user-images.githubusercontent.com/68098335/210327551-01aeacbc-5c40-42b0-90e0-9a81b3760ae3.png)

**Comment by terjeio** [comment]
Did you follow the ["How to use"](https://mdac.com.au/2018/01/14/programming-the-arduino-due-with-bossa/) instructions? If this failed is your board broken? Time to contact the vendor?

**Comment by Ramr93** [comment]
hello sir.. can you  provide any video tutorial to upload the grblhal on Arduino mega 2560?

**Comment by terjeio** [comment]
>  can you provide any video tutorial to upload the grblhal on Arduino mega 2560?

No, since grblHAL cannot run efficiently (or at all?) on a 8-bit processor. So there is currently no 8-bit driver available and I have no plans to write any.

**Comment by Ramr93** [comment]
thank you
