### ISSUE TITLE
Ramps 1.6 pinmapping makes no sense

### ISSUE THREAD

**Issue by MrAntza99** [grblHAL/SAM3X8E#9]
Pins are not making sense of their defines
e.g. X_STEP_PIN is not 16 (or A0 as commend says) but its 54 on Arduino Due + Ramps
Z_STEP_PIN should be pin 46 on Arduino Due so comment is this time correct but actual define isn't

How this should work or edited to work? This is unchanged original file which just fries my board if use even this should be made for Arduino Due + Ramps

![image](https://user-images.githubusercontent.com/43236706/165915421-0f57270c-a089-4f87-a12b-3d10b39d2c02.png)

**Comment by terjeio** [comment]
> e.g. X_STEP_PIN is not 16 (or A0 as commend says) but its 54 on Arduino Due + Ramps

The pin definition is correct, at least for this pin - there are different ways to define them. The driver uses the native MCU port/pin designations (in the yellow boxes below):
![00e75eed26785f26554e2cc120295278](https://user-images.githubusercontent.com/20260062/165920099-08bab35b-2820-4375-a44f-50fa0738b922.png)

> This is unchanged original file which just fries my board ...

It should not - note that the Due I/O is 3.3V, the Ramps board is 5V as it is designed for the Arduino Mega. It needs to be [modified for the Due](https://reprap.org/forum/read.php?219,479626,479837#msg-479837).

**Comment by MrAntza99** [comment]
Hi, thanks and sorry for trouble, I could not just figure out that it was different way to mark pins, it makes a lot confusion but helpful community just told same than u so I understand now better how those are defined, not by Digital Pin name, but Port Pin name :)

Im trying to modify this now for Ramps SMART which I have to use, Im checking all pins and redefine correcponding pins if theres changes between Ramps 1.6 and Ramps Smart
